language: cpp

compilers:
  - gcc
  - clang

matrix:
 include:
   - os: linux
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - gcc-8
           - g++-8
     env:
       - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
   - os: linux
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
           - llvm-toolchain-trusty-5.0
         packages:
           - clang-5.0
     env:
       - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
       
      
      
before_install:
  - eval "${MATRIX_EVAL}"



install:
 - |
   CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
   mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
   ls
   pwd
   export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
 - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  
