# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master
    - production

image: Visual Studio 2017

install:
 - cinst ninja


configuration: Release

platform:
  - x86
  - x64

for:
  - matrix:
      only:
        - platform: x86
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - matrix:
      only:
        - platform: x64
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"



build_script:
  - md build
  - cd build
  - cmake -GNinja ..
  - ninja
